### ISSUE TITLE
Sharing a presentation I made with this, thanks for this! 🙏

### ISSUE THREAD

**Issue by pietroppeter** [bouzidanas/streamlit-reveal-slides#2]
Hi, I used this component for a presentation I made yesterday at the local Python meetup here in Milan and it worked pretty well, thanks a lot for making this available for everyone!

FYI, presentation is here: https://example-driven-learning.streamlit.app/
And there is a full recording of the presentation: https://www.youtube.com/live/YHmp9X5Klr8?si=DAZCgqxFfylUb06N&t=406

**Comment by bouzidanas** [comment]
Thats really cool. I like how you organized your projects with the slides in the streamlit app so that you can easily go to each project separately during/after the presentation. All in one place! Makes me think of the possibility of using slides for separate tutorials on how to use the individual apps.

**Comment by pietroppeter** [comment]
Thanks. I think this component has great potential for creative and effective use cases along with streamlit! I will likely keep using it and report back.

**Comment by bouzidanas** [comment]
That would be really helpful thank you!
